### ISSUE TITLE
Clarify the presentation creation R&R

### ISSUE THREAD

**Issue by anssiko** [w3c/machine-learning-workshop#41]
Should we explicitly note in https://www.w3.org/2020/06/machine-learning-workshop/speakers.html#how who (W3C Staff/PC/speaker) is responsible for combining the presentation slides with the audio/video recording? Currently the instructions do not say who’s job that is (”These two elements will then be synchronized”). This may cause some hesitation for speakers. My expectation is W3C Staff will handle that part.

**Comment by dontcallmedom** [comment]
I have prepared a draft email in #42 to collect the information we will want to share with the accepted speakers.
