### ISSUE TITLE
Packing operations for gemm

### ISSUE THREAD

**Issue by kpu** [w3c/machine-learning-workshop#85]
Hello from [machine translation](https://www.w3.org/2020/06/machine-learning-workshop/talks/privacy_focused_machine_translation_in_firefox.html).  We'd like to run inference as a web extension but the lowest-common-denominator approach taken by Web Assembly means [8-bit GEMM is too far from native](https://github.com/WebAssembly/simd/issues/328). So I'm happy to see [8-bit GEMM](https://webmachinelearning.github.io/webnn/#api-neuralnetworkcontext-gemm). 

Most GEMM implementations have a packed representation. Some support packing in advance, like MKL does for float32 and oneDNN does for int8 if you know where to look while not officially supporting it.  This is particularly useful for inference where usually one of the parameters is a constant.  So a common use case is downloading parameters in some canonical format (row major or whatever), packing it ideally in-place (and throwing away the canonical form to save RAM), then passing the packed format to GEMM.  The packed format is opaque and varies by hardware due to SIMD lengths etc.  Throwing away the canonical form is key because otherwise it effectively doubles RAM requirements for the model.  

In theory a compiler with whole-program knowledge could pack in advance and throw away the canonical form.  But in practice it's theoretically possible some new code will read the canonical values.  So packing is usually done explicitly by the user.  Or there would need to be a slow path that unpacks the values to emulate a canonical read.  

Would you consider adding optional packing operators for a and b?

**Comment by dontcallmedom** [comment]
@huningxin any insight on this?

**Comment by anssiko** [comment]
@kpu, thanks for the suggestion. I believe this feature request is for the WebNN API specifically? If so, I'd suggest we transfer this issue to that spec repo for consideration so it gets the attention of the whole group designing that specific API (only a subset of that group watches this workshop repo). No worries opening the issue in this repo, it can be easily transferred.

**Comment by kpu** [comment]
Sure, belongs in WebNN.  I've moved there: https://github.com/webmachinelearning/webnn/issues/86 .
